02-04-lesson: delete code chunk `load-pkg`
OpenIntroStat/ims-tutorials pull request #40
Opened 2021-04-04 19:39 UTC by petzi53

Both libraries are already loaded in the setup chunk. Reloading `openintro` destroys changes in the setup chunk to the variable `spam` from the `email` dataset. Exercises that relied on these changes did not work correctly.

2021-04-04 20:28 UTC, mine-cetinkaya-rundel commented
Instead of deleting the chunk, it would be better to show it and make it `eval = FALSE` so that students get used to seeing that.

2021-04-04 20:29 UTC, mine-cetinkaya-rundel requested changes
Instead of deleting the chunk, it would be better to leave it and use `eval = FALSE` so that students get used to seeing the packages loaded.

2021-04-05 11:26 UTC, petzi53 commented
You are right, but in that case, one has also to add 'echo = TRUE'.

2021-04-05 11:28 UTC, mine-cetinkaya-rundel commented
Agreed. Let me know if you'd like me to make the change of if you wanted to make and push into this PR.

2021-04-05 11:28 UTC, mine-cetinkaya-rundel approved these changes

2021-04-05 11:29 UTC, merged

2021-04-05 11:29 UTC, mine-cetinkaya-rundel commented
Thank you!